version: '3.3'
services:

  db:
    image: postgres:13.0-alpine
    restart: always
    volumes:
      - db_value:/var/lib/postgresql/data/
    env_file:
      - ./.env

  backend:
    restart: always
    build: vladimirpichuev/foodest_backend/
    volumes:
      - static_value:/static/
      - media_value:/media/
    depends_on:
      - db
    env_file:
      - ./.env

  nginx:
    image: vladimirpichuev/food_nginx
    ports:
      - "8000:80"
    volumes:
      - ./infra/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./frontend/build:/usr/share/nginx/html/
      - ../docs/:/usr/share/nginx/html/api/docs/
      - static:/static/
      - media:/media/
    depends_on:
      - backend

  
  frontend:
    image: vladimirpichuev/food_frontend
    env_file: .env
    command: cp -r /app/build/. /frontend_static/
    volumes:
      - static:/frontend_static



volumes: 
  static_value:
  media_value:
  db_value:
  static:
  media:
  pg_data:
  redoc: