# Generated by Django 5.0 on 2024-01-25 06:14

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reciep',
            name='cooking_time',
            field=models.PositiveSmallIntegerField(validators=[django.core.validators.MaxValueValidator(300, message='Имеет ли смысл так долго готовить?'), django.core.validators.MinValueValidator(1, message='Вы хотите добавить салат змейка?:)')], verbose_name='Время приготовления в минутах'),
        ),
        migrations.AlterField(
            model_name='reciep',
            name='image',
            field=models.ImageField(null=True, upload_to='reciep_photo/%Y/%m/%d/', verbose_name='Изображение'),
        ),
    ]
