# Generated by Django 5.0 on 2024-01-25 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0002_alter_reciep_cooking_time_alter_reciep_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reciep',
            name='content',
            field=models.TextField(verbose_name='Описание рецепта'),
        ),
    ]
